/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIBillet;

import GUI.GUIMenu;

/**
 *
 * @author s104659
 */
public class GUIKortBetaling extends javax.swing.JFrame {

    /**
     * Creates new form GUIKortBetaling
     */
    public GUIKortBetaling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        knap1Pin = new javax.swing.JButton();
        knap2Pin = new javax.swing.JButton();
        knap4Pin = new javax.swing.JButton();
        knap5Pin = new javax.swing.JButton();
        knap3Pin = new javax.swing.JButton();
        Knap6Pin = new javax.swing.JButton();
        knap7Pin = new javax.swing.JButton();
        knap8Pin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        knap9Pin = new javax.swing.JButton();
        pinkodeText = new javax.swing.JTextField();
        annulleringsKnap = new javax.swing.JButton();
        godkendBetalingsKnap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        knap1Pin.setText("1");
        knap1Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap1PinActionPerformed(evt);
            }
        });

        knap2Pin.setText("2");
        knap2Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap2PinActionPerformed(evt);
            }
        });

        knap4Pin.setText("4");
        knap4Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap4PinActionPerformed(evt);
            }
        });

        knap5Pin.setText("5");
        knap5Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap5PinActionPerformed(evt);
            }
        });

        knap3Pin.setText("3");
        knap3Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap3PinActionPerformed(evt);
            }
        });

        Knap6Pin.setText("6");
        Knap6Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Knap6PinActionPerformed(evt);
            }
        });

        knap7Pin.setText("7");
        knap7Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap7PinActionPerformed(evt);
            }
        });

        knap8Pin.setText("8");
        knap8Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap8PinActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText(" Indtast Pinkode");

        knap9Pin.setText("9");
        knap9Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap9PinActionPerformed(evt);
            }
        });

        annulleringsKnap.setText("annullere");
        annulleringsKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulleringsKnapActionPerformed(evt);
            }
        });

        godkendBetalingsKnap.setText("Godkend");
        godkendBetalingsKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godkendBetalingsKnapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(annulleringsKnap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(godkendBetalingsKnap)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(pinkodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(knap7Pin)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(knap8Pin))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(knap4Pin)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(knap5Pin))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(knap1Pin)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(knap2Pin)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(knap3Pin)
                                        .addComponent(Knap6Pin)
                                        .addComponent(knap9Pin)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(139, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulleringsKnap)
                    .addComponent(godkendBetalingsKnap))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(pinkodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(knap3Pin)
                        .addComponent(knap2Pin)
                        .addComponent(knap1Pin))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Knap6Pin)
                        .addComponent(knap5Pin)
                        .addComponent(knap4Pin))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(knap9Pin)
                        .addComponent(knap8Pin)
                        .addComponent(knap7Pin))
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void annulleringsKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulleringsKnapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulleringsKnapActionPerformed

    private void godkendBetalingsKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godkendBetalingsKnapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_godkendBetalingsKnapActionPerformed

    private void knap1PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap1PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knap1PinActionPerformed

    private void knap2PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap2PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knap2PinActionPerformed

    private void knap3PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap3PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knap3PinActionPerformed

    private void knap4PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap4PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knap4PinActionPerformed

    private void knap5PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap5PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knap5PinActionPerformed

    private void Knap6PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Knap6PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Knap6PinActionPerformed

    private void knap7PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap7PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knap7PinActionPerformed

    private void knap8PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap8PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knap8PinActionPerformed

    private void knap9PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap9PinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knap9PinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIKortBetaling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIKortBetaling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIKortBetaling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIKortBetaling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIKortBetaling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Knap6Pin;
    private javax.swing.JButton annulleringsKnap;
    private javax.swing.JButton godkendBetalingsKnap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton knap1Pin;
    private javax.swing.JButton knap2Pin;
    private javax.swing.JButton knap3Pin;
    private javax.swing.JButton knap4Pin;
    private javax.swing.JButton knap5Pin;
    private javax.swing.JButton knap7Pin;
    private javax.swing.JButton knap8Pin;
    private javax.swing.JButton knap9Pin;
    private javax.swing.JTextField pinkodeText;
    // End of variables declaration//GEN-END:variables
}
