/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BT.Betaling;
import BT.BilletTyper;



/**
 *
 * @author s104659
 */
public class GUIMenu extends javax.swing.JPanel {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    BilletTyper billetTyper = new BilletTyper(24, 12);
    Betaling betaling = new Betaling();


    private int k1krone;
    private int k2krone;
    private int k5krone;
    private int k10krone;
    private int k20krone;
    private int k100krone;



    //  set metode for ovenståene instans variabler/felter
    public void setK1krone(int k1krone) { this.k1krone = k1krone; }
    public void setK2krone(int k2krone) { this.k2krone = k2krone; }
    public void setK5krone(int k5krone) { this.k5krone = k5krone; }
    public void setK10krone(int k10krone) { this.k10krone = k10krone; }
    public void setK20krone(int k20krone) { this.k20krone = k20krone; }
    public void setK100krone(int k100krone) { this.k100krone = k100krone; }

    //  get metode for ovenstående instans variabler
    public int getK1krone() { return k1krone; }
    public int getK2krone() { return k2krone; }
    public int getK5krone() { return k5krone; }
    public int getK10krone() { return k10krone; }
    public int getK20krone() { return k20krone; }
    public int getK100krone() { return k100krone; }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        textVoksen = new javax.swing.JTextField();
        textBarn = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        knapKortBetaling = new javax.swing.JButton();
        voksenLabel = new javax.swing.JLabel();
        knap20Kroner = new javax.swing.JButton();
        labelBalance = new javax.swing.JLabel();
        balanceTextfelt = new javax.swing.JTextField();
        knap1Krone = new javax.swing.JButton();
        knap2Kroner = new javax.swing.JButton();
        knap5Kroner = new javax.swing.JButton();
        knap10Kroner = new javax.swing.JButton();
        barnLabel = new javax.swing.JLabel();
        spinnerVoksen = new javax.swing.JSpinner();
        spinnerBarn = new javax.swing.JSpinner();
        knap100Kroner = new javax.swing.JButton();

        textVoksen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        textBarn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalLabel.setText("Total");

        textTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        knapKortBetaling.setText("Kortbetaling");
        knapKortBetaling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knapKortBetalingActionPerformed(evt);
            }
        });

        voksenLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        voksenLabel.setText("Voksen");

        knap20Kroner.setText("20 Kr");
        knap20Kroner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap20KronerActionPerformed(evt);
            }
        });

        labelBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBalance.setText("Balance");

        balanceTextfelt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balanceTextfelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceTextfeltActionPerformed(evt);
            }
        });

        knap1Krone.setText("1 Kr");
        knap1Krone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap1KroneActionPerformed(evt);
            }
        });

        knap2Kroner.setText("2 Kr");
        knap2Kroner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap2KronerActionPerformed(evt);
            }
        });

        knap5Kroner.setText("5 Kr");
        knap5Kroner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap5KronerActionPerformed(evt);
            }
        });

        knap10Kroner.setText("10 Kr");
        knap10Kroner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap10KronerActionPerformed(evt);
            }
        });

        barnLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barnLabel.setText("Barn");

        spinnerVoksen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerVoksen.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        spinnerVoksen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerVoksenStateChanged(evt);
            }
        });

        spinnerBarn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerBarn.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        spinnerBarn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerBarnStateChanged(evt);
            }
        });

        knap100Kroner.setText("100 Kr");
        knap100Kroner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knap100KronerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(barnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(spinnerBarn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(voksenLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(spinnerVoksen, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(textVoksen)
                                                        .addComponent(textBarn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(totalLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(knap1Krone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(knap2Kroner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelBalance)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(balanceTextfelt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(knap20Kroner, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(knap5Kroner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(knap10Kroner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(knap100Kroner, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                                .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(knapKortBetaling, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(81, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelBalance)
                                        .addComponent(totalLabel)
                                        .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(balanceTextfelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(voksenLabel)
                                                        .addComponent(spinnerVoksen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textVoksen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(barnLabel)
                                                        .addComponent(spinnerBarn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textBarn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(knap1Krone)
                                                        .addComponent(knap2Kroner))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(knap5Kroner)
                                                        .addComponent(knap10Kroner))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(knap20Kroner)
                                                        .addComponent(knap100Kroner))))
                                .addGap(55, 55, 55)
                                .addComponent(knapKortBetaling)
                                .addGap(20, 20, 20))
        );
    }// </editor-fold>




    public String voksenFunktion()
    {
        Object o = spinnerVoksen.getValue();
        Number n = (Number) o;

        int voksenValue = n.intValue();
        int voksenP = billetTyper.getVoksenpris();

        int voksenTotal = voksenValue * voksenP;
        String voksenPris = Integer.toString(voksenTotal);
        return voksenPris;
    }

    public String borneFunktion()
    {
        Object o = spinnerBarn.getValue();
        Number n = (Number) o;

        int barnValue = n.intValue();
        int barnP = billetTyper.getBornepris();

        int barnTotal = barnValue * barnP;
        String bornePris = Integer.toString(barnTotal);
        return bornePris;
    }

    public int textTotalFunktion()
    {
        Object objVoksen = spinnerVoksen.getValue();
        Number numVoksen = (Number) objVoksen;

        int voksenValue = numVoksen.intValue();
        int voksenP = billetTyper.getVoksenpris();
        int voksenTotal = voksenValue * voksenP;


        Object objBarn = spinnerBarn.getValue();
        Number numBarn = (Number) objBarn;

        int barnValue = numBarn.intValue();
        int barnP = billetTyper.getBornepris();
        int barnTotal = barnValue * barnP;

        int total = voksenTotal + barnTotal;
        return total;

    }

    private void knapKortBetalingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knapKortBetalingActionPerformed

        GUIKortBetaling kb = new GUIKortBetaling();
        kb.setVisible(true);


    }//GEN-LAST:event_knapKortBetalingActionPerformed


    private void knap1KroneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap1KroneActionPerformed

         setK1krone(1);
         betaling.setBalance(getK1krone());

        balanceTextfelt.setText(totalBalance());
    }//GEN-LAST:event_knap1KroneActionPerformed

    private void knap2KronerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap2KronerActionPerformed

        setK2krone(2);
        betaling.setBalance(getK2krone());

        balanceTextfelt.setText(totalBalance());
    }//GEN-LAST:event_knap2KronerActionPerformed

    private void knap5KronerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap5KronerActionPerformed

        setK5krone(5);
        betaling.setBalance(getK5krone());

        balanceTextfelt.setText(totalBalance());
    }//GEN-LAST:event_knap5KronerActionPerformed

    private void knap10KronerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap10KronerActionPerformed

        setK10krone(10);
        betaling.setBalance(getK10krone());

        balanceTextfelt.setText(totalBalance());
    }//GEN-LAST:event_knap10KronerActionPerformed

    private void knap20KronerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap20KronerActionPerformed

        setK20krone(20);

        betaling.setBalance(getK20krone());
        balanceTextfelt.setText(totalBalance());
    }//GEN-LAST:event_knap20KronerActionPerformed

    private void knap100KronerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knap100KronerActionPerformed

        setK100krone(100);

        betaling.setBalance(getK100krone());
        balanceTextfelt.setText(totalBalance());
    }//GEN-LAST:event_knap100KronerActionPerformed

    private void spinnerVoksenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerVoksenStateChanged

        textVoksen.setText( voksenFunktion() );
        String totalPris = Integer.toString(textTotalFunktion());
        textTotal.setText(totalPris);
    }//GEN-LAST:event_spinnerVoksenStateChanged



    private void spinnerBarnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerBarnStateChanged

        textBarn.setText( borneFunktion());
        String totalPris = Integer.toString(textTotalFunktion());
        textTotal.setText(totalPris);
    }//GEN-LAST:event_spinnerBarnStateChanged

    private void balanceTextfeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceTextfeltActionPerformed

    }//GEN-LAST:event_balanceTextfeltActionPerformed




    public String totalBalance()
    {

        int balanceBetaling = betaling.getBalance();

        String totalbalance = Integer.toString(balanceBetaling);

        if (balanceBetaling < textTotalFunktion() )
        {
            balanceTextfelt.setText(totalbalance);
        }
        else
        {
            GUIBilletKvitering b = new GUIBilletKvitering();
            b.setVisible(true);
        }

        return totalbalance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceTextfelt;
    private javax.swing.JLabel barnLabel;
    private javax.swing.JButton knap100Kroner;
    private javax.swing.JButton knap10Kroner;
    private javax.swing.JButton knap1Krone;
    private javax.swing.JButton knap20Kroner;
    private javax.swing.JButton knap2Kroner;
    private javax.swing.JButton knap5Kroner;
    private javax.swing.JButton knapKortBetaling;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JSpinner spinnerBarn;
    private javax.swing.JSpinner spinnerVoksen;
    private javax.swing.JTextField textBarn;
    private javax.swing.JTextField textTotal;
    private javax.swing.JTextField textVoksen;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel voksenLabel;
    // End of variables declaration//GEN-END:variables
}
