/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeansgui;

import BilletAutomat.BilletAutomatKlasse;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Emily
 */
public class Grafikpanel extends javax.swing.JPanel {


    BilletAutomatKlasse b;
    
    
    /**
     * Creates new form Grafikpanel
     */
    public Grafikpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voksen = new javax.swing.JLabel();
        kortbetaling = new javax.swing.JButton();
        barn = new javax.swing.JLabel();
        tillæg = new javax.swing.JLabel();
        spinnerVoksen = new javax.swing.JSpinner();
        spinnerBarn = new javax.swing.JSpinner();
        spinnerTillæg = new javax.swing.JSpinner();
        hund = new javax.swing.JLabel();
        spinnerhund = new javax.swing.JSpinner();
        tekstfeltVoksen = new javax.swing.JTextField();
        tekstfeltBarn = new javax.swing.JTextField();
        tekstfeltTillæg = new javax.swing.JTextField();
        tekstfeltHund = new javax.swing.JTextField();
        kontantbetaling = new javax.swing.JButton();

        voksen.setText("Voksen");

        kortbetaling.setText("Kortbetaling");
        kortbetaling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kortbetalingActionPerformed(evt);
            }
        });

        barn.setText("Barn");

        tillæg.setText("Tillæg");

        hund.setText("Hund");

        kontantbetaling.setText("Kontantbetaling");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(kortbetaling)
                        .addGap(60, 60, 60)
                        .addComponent(kontantbetaling))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(hund)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinnerhund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tillæg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinnerTillæg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(barn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinnerBarn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(voksen)
                                .addGap(20, 20, 20)
                                .addComponent(spinnerVoksen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tekstfeltBarn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tekstfeltVoksen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tekstfeltTillæg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(tekstfeltHund, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voksen)
                    .addComponent(spinnerVoksen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tekstfeltVoksen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spinnerBarn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tekstfeltBarn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tillæg)
                    .addComponent(spinnerTillæg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tekstfeltTillæg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hund)
                    .addComponent(spinnerhund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tekstfeltHund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kortbetaling)
                    .addComponent(kontantbetaling))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kortbetalingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kortbetalingActionPerformed
        /*
        Noget I STIL MED:
        
        GrafikpanelKortbetaling panel = new GrafikpaneKortbetalingl();        // opret panelet
                panel.b = b;
		JFrame vindue = new JFrame("Grafikpanel");    // opret et vindue på skærmen
		vindue.add( panel );                          // vis panelet i vinduet
                
		vindue.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // reagér på luk
		vindue.setSize(850,470);                       // sæt vinduets størrelse
		vindue.setVisible(true);                      // åbn vinduet
        
        */
    }//GEN-LAST:event_kortbetalingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barn;
    private javax.swing.JLabel hund;
    private javax.swing.JButton kontantbetaling;
    private javax.swing.JButton kortbetaling;
    private javax.swing.JSpinner spinnerBarn;
    private javax.swing.JSpinner spinnerTillæg;
    private javax.swing.JSpinner spinnerVoksen;
    private javax.swing.JSpinner spinnerhund;
    private javax.swing.JTextField tekstfeltBarn;
    private javax.swing.JTextField tekstfeltHund;
    private javax.swing.JTextField tekstfeltTillæg;
    private javax.swing.JTextField tekstfeltVoksen;
    private javax.swing.JLabel tillæg;
    private javax.swing.JLabel voksen;
    // End of variables declaration//GEN-END:variables
}
