/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeansgui;

import BilletAutomat.BilletAutomatKlasse;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Emily
 */
public class Grafikpanel extends javax.swing.JPanel {


    BilletAutomatKlasse b;
    
    
    /**
     * Creates new form Grafikpanel
     */
    public Grafikpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voksen = new javax.swing.JLabel();
        kortbetaling = new javax.swing.JButton();
        tekstfeltVoksen = new javax.swing.JTextField();

        voksen.setText("Voksen");

        kortbetaling.setText("Kortbetaling");
        kortbetaling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kortbetalingActionPerformed(evt);
            }
        });

        tekstfeltVoksen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstfeltVoksenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voksen)
                        .addGap(53, 53, 53)
                        .addComponent(tekstfeltVoksen, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kortbetaling))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voksen)
                    .addComponent(tekstfeltVoksen, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(kortbetaling)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kortbetalingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kortbetalingActionPerformed
        /*
        Noget I STIL MED:
        
        GrafikpanelKortbetaling panel = new GrafikpaneKortbetalingl();        // opret panelet
                panel.b = b;
		JFrame vindue = new JFrame("Grafikpanel");    // opret et vindue på skærmen
		vindue.add( panel );                          // vis panelet i vinduet
                
		vindue.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // reagér på luk
		vindue.setSize(850,470);                       // sæt vinduets størrelse
		vindue.setVisible(true);                      // åbn vinduet
        
        */
    }//GEN-LAST:event_kortbetalingActionPerformed

    private void tekstfeltVoksenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstfeltVoksenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekstfeltVoksenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton kortbetaling;
    private javax.swing.JTextField tekstfeltVoksen;
    private javax.swing.JLabel voksen;
    // End of variables declaration//GEN-END:variables
}
